theme: minima
url: "https://lisa-youngbin.github.io"
description: Lisa Kim | PhD Candidate in Neuroscience at Northwestern University | Awatramani Lab
author:
  name: "Lisa Kim"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
