theme: minima
url: "https://lisa-youngbin.github.io"
title: Lisa Kim
description: Personal academic website of Lisa Kim, PhD Candidate in Neuroscience at Northwestern University studying dopamine.
author:
  name: "Lisa Kim"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
